### ISSUE TITLE
feat: Changing the build system to cmake

### ISSUE THREAD

**Issue by kevinalavik** [aurixos/kernel#1]
Switching to cmake would be a more "proper" build system. This allows the user to easily change custom "targets" aka toolchain files (https://cmake.org/cmake/help/latest/envvar/CMAKE_TOOLCHAIN_FILE.html). And also using ninja (https://ninja-build.org/) would be a great idea too since it’s faster then make. Also a proper system to configure aurix and build (using like bash scripts). This is what I do in leaf and is totally a personal preference but I think it’s wise to switch since it’s easier to scale the project. If you need any help I would be more then happy to help!

**Comment by cre0z** [comment]
I'm still a bit worried about switching to CMake fully - especially making sure the entire system is easily expandable for other architectures and easy to understand. I'll probably make a new branch to do some experiments with CMake.

**Comment by kevinalavik** [comment]
Yep i fully understand but i honestly think cmake syntax is easier to understand then make. And for other architectures you could do as i said in the first comment. Use toolchain files. In leaf i also have like a gen-$bootloader.sh script to generate the final image. So the configure and build system uses the cmake to configure and ninja to build then makes a image with a predefined script based on arch and bootloader. And i think a new branch would be wise. I would love to help

**Comment by cre0z** [comment]
Closing for settling with Make.

**Comment by kevinalavik** [comment]
@schkwve fair enough.
